<h1>Appendix A - Documents</h1>
<h3 style ="margin-top: 10px;">Figure 3: Table of Documents</h3>
<table id ="doctable" class="display">
	<thead><tr><th>Date</th><th>No.</th><th>Inst.</th><th>Type</th><th>Book / Page</th><th>Plan Name</th><th>Reg. System</th><th>Filing Reference</th><th>Drawer No.</th><th>File</th></tr></thead><tbody>
		 <tr><td>2015/03/16</td><td>266947</td><td>Non-Registered</td><td>Notice Of Death</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>VS2014009418</td><td>&nbsp;</td><td><div class="table-link"><a href="http://necrologie.genealogiequebec.com/avis-de-deces/1578522-DOWNEY-Hazel"><span class="glyphicon glyphicon glyphicon-link" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>2013/10/01</td><td>&nbsp;</td><td>Map</td><td>LTCA</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/LTCA-North-Preston.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1993/12/01</td><td>29656</td><td>Plan</td><td>Subdivision and Amalgamation</td><td>&nbsp;</td><td>Lot 720B-Z, 72-X-Y</td><td>&nbsp;</td><td>&nbsp;</td><td>316</td><td><div class="table-link"><a href="POLDocs/29656_SubdivisionAndAmalgamations.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1993/12/01</td><td>50439</td><td>Document</td><td>Approval of Plan of Subdivision</td><td>Book 5500 Page 402</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/50439_Approval_Of_Plans.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1991/07/23</td><td>29712</td><td>Document</td><td>Deed</td><td>Book 5106 Page 267</td><td>&nbsp;</td><td>Registry of Deeds</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/29712_PrincipleDowneyDeed.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1989/09/29</td><td>26613</td><td>Plan</td><td>Subdivision and Amalgamations</td><td>&nbsp;</td><td>Lots 72-A & 72- B</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/26613_SubdivisionAndAmalgamations.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1989/09/01</td><td>53033</td><td>Other Instruments</td><td>Approval of Plan of Subdivision</td><td>Book 4817 Page 163</td><td>&nbsp;</td><td>Registry of Deeds</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/53033_Approval_Of_Plans.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1986/03/01</td><td>15536</td><td>Document</td><td>Quieting of / Certificate of Title</td><td>Book 4142 Page 808</td><td>&nbsp;</td><td>Registry of Deeds</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/15536_Quietingof_CertificateOfTitle.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1985/10/01</td><td>63570</td><td>Document</td><td>Certificate of Claim</td><td>Book 4071 Page 220</td><td>&nbsp;</td><td>Registry of Deeds</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/63570_CertificateofClaim.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1985/01/01</td><td>40710220</td><td>Plan</td><td>Document Attachment</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/40710220_DocumentAttachment_to_CertificateofClaim.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>1972/01/01</td><td>180041420808</td><td>Plan</td><td>Retracement & Plan or Return of Survey</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>230</td><td><div class="table-link"><a href="POLDocs/180041420808_RetracementPlan.pdf"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a></div></td></tr>
		 <tr><td>2017/01/29</td><td>&nbsp;</td><td>Spreadsheet</td><td>Property Coordinates Spreadsheet</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td><div class="table-link"><a href="POLDocs/DowneyLotsCoordinates.xlsx"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span></a></div></td></tr>
	</tbody>
</table><!--End Row-->