<div class = "full-width">
		<h1>Findings</h1>
		<p class="pol-article">
		On October 15th 1985, the Crown certified that Ms. Hazel Mae Downey is entitled to a claim of a lot of land of approximately 1.9 acres in New Road Settlement, pursuant to the provisions of the Land Titles Clarification Act approved by the Council of the Municipality of the County of Halifax on July 21st 1964. Attached with the certificate of claim was a copy of Field Plot No. P-107/72 signed June 13th 1972, by Murray J. Banks, NSLS, designating Lot 72. Three dwellings existing within the boundaries of Lot 72 are shown. On January 15th 1986, Ms. Downey was granted a certificate of title by Ken Streatch, Minister of Lands and Forests for the Province of Nova Scotia. 
		<br><br>On October 18th 1988, and on April 5th & 6th 1989, a survey of Lot 72 was completed by Donald V. Purcell, NSLS. A plan of subdivision entered and filed on September 29th 1989, designating lots 72-A, 72-B and 72-R. Two dwellings existing within the boundary of Lot 72-R are shown as well as a third structure owned by Ms. Hazel Mae Downey's daugther, Ms. Principle Downey. This dwelling is shown to lay across the boundaries of Lot 72-R and (then) ungranted crown land (PID: 40818411).
		<br><br>On July 23rd 1991 Ms. Hazel Mae Downey conveys lot 72-B to Ms. Principle Downey and a deed is filed in Book 5106, Page 267 at the Registry of Deeds Office in the County of Halifax.
		<br><br>On November 5th 1993 a plan of subdivision showing lots 72/72-R, 72-A, 72-B-Z  and 72-X-Y is filed by Donald V. Purcell, NSLS. On November 26th 1993 the plan of subdivision is approved and signed by the Municipal Development Officer on December 1st 1993. Lot 72-B-Z is formed by an addition of a portion of Lot 72, Lot 72-X-Y is formed by portions of Lots 72 and 72-B. This plan shows the demolition of the dwelling which lied accross Lot-72-R and crown land, shown in the plan entered and filed on September 29th 1989. The plan entered on November 26th 1993 shows the construction of a new dwelling owned by Ms. Principle Downey laying across Lot 72-B and Lot 72-R. The Lot 72-X-Y is formed surrounding the aforementioned structure so as to contain it within one lot and the boundaries of the other lots adjusted accordingly.
		<br><br>On December 27th 2014 Ms. Hazel Mae Downey passed away. Her obituary is published January 1st 2015. A notice of death is filed on March 16th 2015 with Service Nova Scotia.
		<br></br>
		Refer to <a href="#docs">[Appendix A - Documents]</a></li> for all documents cited in this section.</p>
</div>